import jsPDF from 'jspdf';

export interface AIProtectionData {
  userId: string;
  protectedFiles: number;
  protectionMethods: string[];
  certificateDate: Date;
  protectionLevel: string;
  verificationId?: string;
}

export class AIProtectionCertificateGenerator {
  /**
   * Generate a downloadable AI protection certificate
   */
  static generateProtectionCertificate(data: AIProtectionData): Blob {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('AI TRAINING PROTECTION CERTIFICATE', 20, 25);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Official Proof of Content Protection Against Unauthorized AI Training', 20, 35);
    
    // TSMO Protection Badge
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 100, 200);
    doc.text('Protected by TSMO Advanced AI Protection', 20, 45);
    doc.setTextColor(0, 0, 0);
    
    // Horizontal line
    doc.line(20, 50, 190, 50);
    
    // Certificate details
    doc.setFontSize(10);
    let yPos = 62;
    
    const addField = (label: string, value: string, bold: boolean = false) => {
      doc.setFont('helvetica', 'bold');
      doc.text(`${label}:`, 20, yPos);
      doc.setFont('helvetica', bold ? 'bold' : 'normal');
      doc.text(value, 75, yPos);
      yPos += 8;
    };
    
    const certificateId = `AI-CERT-${Date.now().toString(36).toUpperCase()}`;
    addField('Certificate ID', certificateId, true);
    addField('Issued Date', data.certificateDate.toLocaleDateString());
    addField('Protection Level', data.protectionLevel.toUpperCase(), true);
    addField('Protected Files', data.protectedFiles.toString());
    addField('User ID', data.userId.slice(0, 8) + '...');
    
    // Protection Methods section
    yPos += 5;
    doc.setFont('helvetica', 'bold');
    doc.text('Active Protection Methods:', 20, yPos);
    yPos += 8;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    data.protectionMethods.forEach(method => {
      doc.text(`• ${this.getMethodDisplayName(method)}`, 25, yPos);
      yPos += 6;
    });
    
    // Legal Notice section
    yPos += 8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('LEGAL PROTECTION NOTICE', 20, yPos);
    yPos += 10;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    
    const legalText = [
      'This certificate serves as legal proof that the protected content is explicitly',
      'EXCLUDED from use in artificial intelligence training, machine learning model',
      'development, or any automated algorithmic processing without express written',
      'consent from the copyright holder.',
      '',
      'UNAUTHORIZED USE PROHIBITED:',
      '• AI model training or fine-tuning',
      '• Machine learning dataset compilation',
      '• Neural network feature extraction',
      '• Automated content generation based on protected works',
      '• Deep learning algorithm development',
      '',
      'Violation of these protections may result in:',
      '• Legal action under copyright law',
      '• DMCA takedown notices',
      '• Monetary damages and injunctive relief'
    ];
    
    legalText.forEach(line => {
      if (line === '') {
        yPos += 3;
      } else if (line.startsWith('•')) {
        doc.text(line, 25, yPos);
        yPos += 5;
      } else {
        doc.text(line, 20, yPos);
        yPos += 5;
      }
    });
    
    // Verification section
    yPos += 8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.text('Certificate Verification:', 20, yPos);
    yPos += 7;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    
    const verificationHash = this.generateVerificationHash(data);
    const verificationText = [
      `Verification Hash: ${verificationHash}`,
      `Digital Signature: TSMO-${certificateId.slice(-8)}`,
      `Blockchain Record: ${data.verificationId || 'Pending registration'}`,
      '',
      'This certificate is cryptographically verified and legally binding.',
      'To verify authenticity, visit: https://tsmo.ai/verify-certificate'
    ];
    
    verificationText.forEach(line => {
      if (line === '') {
        yPos += 3;
      } else {
        doc.text(line, 20, yPos);
        yPos += 5;
      }
    });
    
    // Footer
    yPos += 10;
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text('Generated by TSMO AI Protection System', 20, yPos);
    doc.text(`Certificate issued on ${new Date().toLocaleString()}`, 20, yPos + 5);
    doc.text('This document is digitally generated, legally valid, and internationally recognized.', 20, yPos + 10);
    
    // Add security watermark
    doc.setFontSize(45);
    doc.setTextColor(245, 245, 245);
    doc.text('PROTECTED', 50, 160, { angle: 45 });
    
    return doc.output('blob');
  }
  
  /**
   * Generate a simple text certificate
   */
  static generateTextCertificate(data: AIProtectionData): Blob {
    const certificateId = `AI-CERT-${Date.now().toString(36).toUpperCase()}`;
    const verificationHash = this.generateVerificationHash(data);
    
    const content = `
AI TRAINING PROTECTION CERTIFICATE
===================================
Protected by TSMO Advanced AI Protection

Certificate ID: ${certificateId}
Issued Date: ${data.certificateDate.toISOString()}
Protection Level: ${data.protectionLevel.toUpperCase()}
Protected Files: ${data.protectedFiles}
User ID: ${data.userId}

ACTIVE PROTECTION METHODS:
${data.protectionMethods.map(method => `- ${this.getMethodDisplayName(method)}`).join('\n')}

LEGAL PROTECTION NOTICE:
This certificate serves as legal proof that the protected content is 
explicitly EXCLUDED from use in artificial intelligence training, 
machine learning model development, or any automated algorithmic 
processing without express written consent from the copyright holder.

UNAUTHORIZED USE PROHIBITED:
- AI model training or fine-tuning
- Machine learning dataset compilation  
- Neural network feature extraction
- Automated content generation based on protected works
- Deep learning algorithm development

Verification Hash: ${verificationHash}
Digital Signature: TSMO-${certificateId.slice(-8)}
Blockchain Record: ${data.verificationId || 'Pending registration'}

Generated by TSMO AI Protection System
Timestamp: ${new Date().toISOString()}

This certificate is legally binding and internationally recognized.
To verify authenticity, visit: https://tsmo.ai/verify-certificate
    `.trim();
    
    return new Blob([content], { type: 'text/plain' });
  }
  
  /**
   * Get display name for protection method
   */
  private static getMethodDisplayName(methodId: string): string {
    const methodNames: Record<string, string> = {
      'invisibleWatermark': 'Invisible Watermarking',
      'adversarialNoise': 'Adversarial Noise Protection',
      'metadataInjection': 'Rights Metadata Injection',
      'blockchainRegistration': 'Blockchain Rights Registration',
      'robotsTxtEntry': 'Web Crawler Blocking',
      'likenenessProtection': 'Likeness Recognition Protection'
    };
    return methodNames[methodId] || methodId;
  }
  
  /**
   * Generate verification hash for certificate authenticity
   */
  private static generateVerificationHash(data: AIProtectionData): string {
    const hashInput = `${data.userId}${data.protectedFiles}${data.protectionMethods.join('')}${data.certificateDate.getTime()}`;
    let hash = 0;
    for (let i = 0; i < hashInput.length; i++) {
      const char = hashInput.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash;
    }
    return Math.abs(hash).toString(16).toUpperCase().padStart(12, '0');
  }
  
  /**
   * Download certificate file
   */
  static downloadCertificate(blob: Blob, format: 'pdf' | 'txt' = 'pdf') {
    const timestamp = new Date().toISOString().split('T')[0];
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `AI_Protection_Certificate_${timestamp}.${format}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}