import jsPDF from 'jspdf';

export interface WatermarkProofData {
  fileName: string;
  watermarkId: string;
  detectionTimestamp: Date;
  confidence: number;
  userId?: string;
  artworkId?: string;
  scanType: string;
}

export class WatermarkProofGenerator {
  /**
   * Generate a downloadable proof certificate for watermark detection
   */
  static generateProofCertificate(data: WatermarkProofData): Blob {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('TSMO Watermark Detection Certificate', 20, 30);
    
    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Official Proof of Digital Watermark Detection', 20, 40);
    
    // Horizontal line
    doc.line(20, 45, 190, 45);
    
    // Certificate details
    doc.setFontSize(10);
    let yPos = 60;
    
    const addField = (label: string, value: string) => {
      doc.setFont('helvetica', 'bold');
      doc.text(`${label}:`, 20, yPos);
      doc.setFont('helvetica', 'normal');
      doc.text(value, 80, yPos);
      yPos += 10;
    };
    
    addField('Certificate ID', `CERT-${data.watermarkId}-${Date.now()}`);
    addField('File Name', data.fileName);
    addField('Watermark ID', data.watermarkId);
    addField('Detection Date', data.detectionTimestamp.toLocaleString());
    addField('Confidence Level', `${data.confidence.toFixed(1)}%`);
    addField('Scan Type', data.scanType);
    
    if (data.userId) {
      addField('User ID', data.userId.slice(0, 8) + '...');
    }
    
    if (data.artworkId) {
      addField('Artwork ID', data.artworkId.slice(0, 8) + '...');
    }
    
    // Verification section
    yPos += 10;
    doc.setFont('helvetica', 'bold');
    doc.text('Verification Details:', 20, yPos);
    yPos += 15;
    
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    
    const verificationText = [
      'This certificate confirms that a TSMO digital watermark was successfully',
      'detected in the specified file using advanced image analysis algorithms.',
      '',
      'Detection Method: Pixel pattern analysis and frequency domain inspection',
      'Algorithm: TSMO Invisible Watermark Detection v2.0',
      `Verification Hash: ${this.generateVerificationHash(data)}`,
      '',
      'This certificate serves as legal proof of watermark presence and can be',
      'used in copyright protection and intellectual property disputes.'
    ];
    
    verificationText.forEach(line => {
      doc.text(line, 20, yPos);
      yPos += 8;
    });
    
    // Footer
    yPos += 20;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Generated by TSMO Copyright Protection System', 20, yPos);
    doc.text(`Certificate generated on ${new Date().toLocaleString()}`, 20, yPos + 8);
    doc.text('This document is digitally generated and legally valid.', 20, yPos + 16);
    doc.text('TSMO Watch is proprietary of TSMO Technology Inc.', 20, yPos + 24);
    
    // Add a watermark to the PDF itself
    doc.setFontSize(40);
    doc.setTextColor(240, 240, 240);
    doc.text('TSMO CERTIFIED', 50, 150, { angle: 45 });
    
    return doc.output('blob');
  }
  
  /**
   * Generate a simple text proof file
   */
  static generateTextProof(data: WatermarkProofData): Blob {
    const content = `
TSMO WATERMARK DETECTION PROOF
==============================

Certificate ID: CERT-${data.watermarkId}-${Date.now()}
File Name: ${data.fileName}
Watermark ID: ${data.watermarkId}
Detection Timestamp: ${data.detectionTimestamp.toISOString()}
Confidence Level: ${data.confidence.toFixed(1)}%
Scan Type: ${data.scanType}
${data.userId ? `User ID: ${data.userId}` : ''}
${data.artworkId ? `Artwork ID: ${data.artworkId}` : ''}

Verification Hash: ${this.generateVerificationHash(data)}

This document certifies that a TSMO digital watermark was successfully 
detected in the specified file using advanced detection algorithms.

Generated by TSMO Copyright Protection System
Timestamp: ${new Date().toISOString()}

TSMO Watch is proprietary of TSMO Technology Inc.
    `.trim();
    
    return new Blob([content], { type: 'text/plain' });
  }
  
  /**
   * Generate verification hash for proof authenticity
   */
  private static generateVerificationHash(data: WatermarkProofData): string {
    const hashInput = `${data.fileName}${data.watermarkId}${data.detectionTimestamp.getTime()}${data.confidence}`;
    // Simple hash function (in production, use crypto.subtle.digest)
    let hash = 0;
    for (let i = 0; i < hashInput.length; i++) {
      const char = hashInput.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash; // Convert to 32-bit integer
    }
    return Math.abs(hash).toString(16).toUpperCase().padStart(8, '0');
  }
  
  /**
   * Download proof file
   */
  static downloadProof(blob: Blob, fileName: string, format: 'pdf' | 'txt' = 'pdf') {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${fileName}_watermark_proof.${format}`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}