import { useState, useEffect } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/components/ui/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { FileText, Clock, AlertTriangle, CheckCircle, Download, Send, ExternalLink } from "lucide-react";
import { DMCAFormDialog } from "@/components/dmca/DMCAFormDialog";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Progress } from "@/components/ui/progress";
import jsPDF from 'jspdf';

interface DMCANotice {
  id: string;
  created_at: string;
  status: string;
  copyright_owner_name: string;
  copyright_owner_email: string;
  copyright_work_description: string;
  infringing_url: string;
  target_domain: string;
  agent_email?: string | null;
  dmca_notice_text?: string;
  // Additional fields that may be present
  [key: string]: any;
}

interface RateLimitStatus {
  allowed: boolean;
  limits: {
    perHour: number;
    perDay: number;
    description: string;
  };
  usage: {
    hourly: number;
    daily: number;
  };
  message: string;
}

export default function DMCACenter() {
  const [dmcaNotices, setDmcaNotices] = useState<DMCANotice[]>([]);
  const [loading, setLoading] = useState(true);
  const [rateLimitStatus, setRateLimitStatus] = useState<RateLimitStatus | null>(null);
  const { toast } = useToast();

  useEffect(() => {
    fetchDMCANotices();
    checkRateLimit();
  }, []);

  const fetchDMCANotices = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data, error } = await supabase
        .from('dmca_notices')
        .select('*')
        .eq('copyright_owner_email', user.email)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setDmcaNotices(data || []);
    } catch (error) {
      console.error('Error fetching DMCA notices:', error);
      toast({
        title: "Error",
        description: "Failed to load DMCA notices",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const checkRateLimit = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;

      const { data, error } = await supabase.functions.invoke('filing-rate-limiter', {
        body: {
          userId: user.email,
          filingType: 'dmca_filing',
          action: 'check'
        }
      });

      if (error) throw error;
      setRateLimitStatus(data);
    } catch (error) {
      console.error('Error checking rate limit:', error);
    }
  };

  const downloadNoticePDF = async (notice: DMCANotice) => {
    try {
      const pdf = new jsPDF();
      
      // Header
      pdf.setFontSize(20);
      pdf.text('DMCA Takedown Notice', 20, 30);
      
      // Notice details
      pdf.setFontSize(12);
      pdf.text(`Notice ID: ${notice.id}`, 20, 50);
      pdf.text(`Date Filed: ${new Date(notice.created_at).toLocaleDateString()}`, 20, 60);
      pdf.text(`Status: ${notice.status}`, 20, 70);
      pdf.text(`Target Domain: ${notice.target_domain}`, 20, 80);
      
      // Content
      pdf.text('Notice Content:', 20, 100);
      const splitText = pdf.splitTextToSize(notice.dmca_notice_text, 170);
      pdf.text(splitText, 20, 110);
      
      // Footer
      pdf.setFontSize(10);
      pdf.text('Generated by TSMO DMCA Center', 20, 280);
      pdf.text(`Download Date: ${new Date().toLocaleDateString()}`, 20, 290);
      
      pdf.save(`DMCA-Notice-${notice.id.slice(-8)}.pdf`);
      
      toast({
        title: "Download Complete",
        description: "DMCA notice PDF has been downloaded"
      });
    } catch (error) {
      console.error('Error generating PDF:', error);
      toast({
        title: "Download Failed",
        description: "Failed to generate PDF",
        variant: "destructive"
      });
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'pending': return 'yellow';
      case 'sent': return 'blue';
      case 'acknowledged': return 'green';
      case 'resolved': return 'green';
      case 'rejected': return 'red';
      default: return 'gray';
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'pending': return Clock;
      case 'sent': return Send;
      case 'acknowledged': return CheckCircle;
      case 'resolved': return CheckCircle;
      case 'rejected': return AlertTriangle;
      default: return FileText;
    }
  };

  if (loading) {
    return (
      <div className="space-y-6">
        <div className="h-8 bg-muted animate-pulse rounded" />
        <div className="grid gap-4">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-32 bg-muted animate-pulse rounded" />
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">DMCA Center</h1>
          <p className="text-muted-foreground">
            Manage your DMCA takedown notices and track their status
          </p>
        </div>
      </div>

      {/* Rate Limit Status */}
      {rateLimitStatus && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Clock className="w-5 h-5" />
              Filing Rate Limits
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <p className="text-sm font-medium">Hourly Usage</p>
                  <Progress 
                    value={(rateLimitStatus.usage.hourly / rateLimitStatus.limits.perHour) * 100} 
                    className="mt-2"
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    {rateLimitStatus.usage.hourly} / {rateLimitStatus.limits.perHour} this hour
                  </p>
                </div>
                <div>
                  <p className="text-sm font-medium">Daily Usage</p>
                  <Progress 
                    value={(rateLimitStatus.usage.daily / rateLimitStatus.limits.perDay) * 100} 
                    className="mt-2"
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    {rateLimitStatus.usage.daily} / {rateLimitStatus.limits.perDay} today
                  </p>
                </div>
              </div>
              
              {!rateLimitStatus.allowed && (
                <Alert>
                  <AlertTriangle className="h-4 w-4" />
                  <AlertDescription>
                    {rateLimitStatus.message}
                  </AlertDescription>
                </Alert>
              )}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Main Content */}
      <Tabs defaultValue="notices" className="space-y-6">
        <TabsList>
          <TabsTrigger value="notices">My DMCA Notices</TabsTrigger>
          <TabsTrigger value="stats">Statistics</TabsTrigger>
          <TabsTrigger value="help">Help & Guidelines</TabsTrigger>
        </TabsList>

        <TabsContent value="notices" className="space-y-4">
          {dmcaNotices.length === 0 ? (
            <Card>
              <CardContent className="pt-6">
                <div className="text-center space-y-4">
                  <FileText className="w-12 h-12 text-muted-foreground mx-auto" />
                  <div>
                    <h3 className="text-lg font-semibold">No DMCA Notices Yet</h3>
                    <p className="text-muted-foreground">
                      You haven't filed any DMCA takedown notices yet. Click "File DMCA Notice" to get started.
                    </p>
                  </div>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4">
              {dmcaNotices.map((notice) => {
                const StatusIcon = getStatusIcon(notice.status);
                return (
                  <Card key={notice.id}>
                    <CardHeader>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-3">
                          <StatusIcon className="w-5 h-5" />
                          <div>
                            <CardTitle className="text-lg">
                              Notice #{notice.id.slice(-8)}
                            </CardTitle>
                            <CardDescription>
                              Filed {new Date(notice.created_at).toLocaleDateString()}
                            </CardDescription>
                          </div>
                        </div>
                        <Badge variant={getStatusColor(notice.status) as any}>
                          {notice.status}
                        </Badge>
                      </div>
                    </CardHeader>
                    <CardContent>
                      <div className="space-y-4">
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          <div>
                            <p className="text-sm font-medium">Target Domain</p>
                            <p className="text-sm text-muted-foreground">{notice.target_domain}</p>
                          </div>
                          <div>
                            <p className="text-sm font-medium">Infringing URL</p>
                            <div className="flex items-center gap-2">
                              <p className="text-sm text-muted-foreground truncate">
                                {notice.infringing_url}
                              </p>
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={() => window.open(notice.infringing_url, '_blank')}
                              >
                                <ExternalLink className="w-4 h-4" />
                              </Button>
                            </div>
                          </div>
                        </div>
                        
                        <div>
                          <p className="text-sm font-medium">Work Description</p>
                          <p className="text-sm text-muted-foreground">
                            {notice.copyright_work_description}
                          </p>
                        </div>

                        <div className="flex gap-2">
                          <Button
                            variant="outline"
                            size="sm"
                            onClick={() => downloadNoticePDF(notice)}
                          >
                            <Download className="w-4 h-4 mr-2" />
                            Download PDF
                          </Button>
                          {notice.agent_email && (
                            <Button
                              variant="outline"
                              size="sm"
                              onClick={() => window.open(`mailto:${notice.agent_email}`, '_blank')}
                            >
                              <Send className="w-4 h-4 mr-2" />
                              Contact Agent
                            </Button>
                          )}
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          )}
        </TabsContent>

        <TabsContent value="stats">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Total Notices</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">{dmcaNotices.length}</p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Pending</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">
                  {dmcaNotices.filter(n => n.status === 'pending').length}
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <CardTitle className="text-lg">Resolved</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-bold">
                  {dmcaNotices.filter(n => ['resolved', 'acknowledged'].includes(n.status)).length}
                </p>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="help">
          <div className="space-y-6">
            <Card>
              <CardHeader>
                <CardTitle>DMCA Filing Guidelines</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div>
                  <h4 className="font-semibold">Before Filing</h4>
                  <ul className="list-disc list-inside text-sm space-y-1 text-muted-foreground">
                    <li>Ensure you own the copyright to the work</li>
                    <li>Verify the content is actually infringing</li>
                    <li>Try contacting the platform directly first</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold">Rate Limits</h4>
                  <ul className="list-disc list-inside text-sm space-y-1 text-muted-foreground">
                    <li>Maximum 5 DMCA notices per hour</li>
                    <li>Maximum 20 DMCA notices per day</li>
                    <li>Limits reset automatically</li>
                  </ul>
                </div>
                <div>
                  <h4 className="font-semibold">Response Times</h4>
                  <ul className="list-disc list-inside text-sm space-y-1 text-muted-foreground">
                    <li>Most platforms respond within 24-48 hours</li>
                    <li>Some may take up to 7 business days</li>
                    <li>You'll receive email notifications on status changes</li>
                  </ul>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}