import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Separator } from '@/components/ui/separator';
import { Progress } from '@/components/ui/progress';
import { useToast } from '@/hooks/use-toast';

import { 
  Shield, 
  Eye, 
  Activity, 
  Link2, 
  Search, 
  Check, 
  Star, 
  ArrowRight,
  Zap,
  Globe,
  Lock,
  TrendingUp,
  Users,
  Mail,
  Phone,
  MapPin,
  FileImage,
  Upload,
  Scan,
  Bot,
  Play,
  ChevronRight,
  Download,
  FileText,
  Scale
} from 'lucide-react';
import jsPDF from 'jspdf';
import tsmoLogo from "@/assets/tsmo-transparent-logo.png";
import MonitoringFlow from "@/components/MonitoringFlow";
import LoadingSpinner from "@/components/LoadingSpinner";

const Index = () => {
  const { toast } = useToast();
  const navigate = useNavigate();
  
  const [demoStep, setDemoStep] = useState(0);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  const startDemo = () => {
    setIsAnalyzing(true);
    setDemoStep(1);
    
    // Simulate analysis steps
    setTimeout(() => setDemoStep(2), 2000);
    setTimeout(() => setDemoStep(3), 4000);
    setTimeout(() => setDemoStep(4), 6000);
    setTimeout(() => {
      setDemoStep(5);
      setIsAnalyzing(false);
    }, 8000);
  };

  const resetDemo = () => {
    setDemoStep(0);
    setIsAnalyzing(false);
  };


  const handlePricingPlan = (plan: string) => {
    toast({
      title: `${plan} Plan Selected`,
      description: "Redirecting to checkout...",
    });
    // Navigate to checkout
    setTimeout(() => {
      navigate(`/checkout?plan=${plan.toLowerCase()}`);
    }, 1500);
  };

  const handleFreeTrial = (plan: string) => {
    toast({
      title: "Free Trial Started!",
      description: `Your 5-day ${plan} trial is now active. Check your email for setup instructions.`,
    });
  };

  const downloadPDF = (title: string, content: string) => {
    try {
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      const lineHeight = 6;
      let yPosition = margin;

      // Header
      pdf.setFontSize(18);
      pdf.setFont('helvetica', 'bold');
      pdf.text(title.toUpperCase(), margin, yPosition);
      yPosition += 15;

      // Separator line
      pdf.setLineWidth(0.5);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // Content
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'normal');
      
      const lines = pdf.splitTextToSize(content.trim(), pageWidth - (2 * margin));
      
      for (let i = 0; i < lines.length; i++) {
        if (yPosition + lineHeight > pageHeight - margin) {
          pdf.addPage();
          yPosition = margin;
        }
        pdf.text(lines[i], margin, yPosition);
        yPosition += lineHeight;
      }

      // Footer
      const footerY = pageHeight - 15;
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'italic');
      pdf.text('Generated by TSMO Legal Templates', margin, footerY);
      pdf.text(`Downloaded: ${new Date().toLocaleDateString()}`, pageWidth - margin - 30, footerY);

      // Save the PDF
      const fileName = `${title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
      pdf.save(fileName);

      toast({
        title: "PDF Downloaded",
        description: `${title} has been downloaded as a PDF.`,
      });
    } catch (error) {
      toast({
        title: "Download Failed",
        description: "There was an error generating the PDF. Please try again.",
        variant: "destructive",
      });
    }
  };
  
  return (
    <div className="min-h-screen bg-white">
      {/* Hero Section */}
      <section className="pt-24 sm:pt-32 pb-20 px-4">
        <div className="container mx-auto text-center max-w-6xl">
          <Badge variant="secondary" className="mb-6 px-3 sm:px-4 py-2 text-xs sm:text-sm">
            🔒 Trusted by 10,000+ Artists Worldwide
          </Badge>
          
          {/* TSMO Logo */}
          <div className="mb-6 sm:mb-8">
            <img 
              src={tsmoLogo} 
              alt="TSMO Multimedia Creative Protection Logo" 
              className="h-48 sm:h-64 md:h-96 lg:h-112 mx-auto object-contain"
            />
          </div>
          
          <h1 className="text-3xl sm:text-4xl md:text-6xl lg:text-7xl font-bold mb-4 sm:mb-6 bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent leading-tight">
            Protect Your Art.<br />
            <span className="text-foreground">Own Your Future.</span>
          </h1>
          
          <p className="text-base sm:text-lg md:text-xl lg:text-2xl text-muted-foreground mb-6 sm:mb-8 max-w-3xl mx-auto leading-relaxed px-4">
            Advanced AI-powered protection for digital artists. Monitor, verify, and secure your creative work 
            with blockchain technology and real-time threat detection.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-3 sm:gap-4 justify-center items-center mb-8 sm:mb-12 px-4">
            {/* Main action buttons */}
            <>
              <Button 
                size="lg" 
                className="w-full sm:w-auto px-6 sm:px-8 py-3 text-base sm:text-lg bg-gradient-to-r from-primary to-accent hover:from-primary/90 hover:to-accent/90"
                onClick={() => navigate("/upload")}
              >
                Upload & Protect Your Art
                <ArrowRight className="ml-2 h-4 w-4 sm:h-5 sm:w-5" />
              </Button>
              <Button 
                variant="outline" 
                size="lg" 
                className="w-full sm:w-auto px-6 sm:px-8 py-3 text-base sm:text-lg"
                onClick={() => navigate("/monitoring")}
              >
                <Activity className="mr-2 h-4 w-4 sm:h-5 sm:w-5" />
                View Dashboard
              </Button>
            </>
          </div>
          
        </div>
      </section>
      
      {/* Stats Section */}
      <section className="bg-gray-50 py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            <div>
              <div className="text-3xl font-bold text-primary">24/7</div>
              <div className="text-sm text-muted-foreground">Monitoring</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-primary">99.9%</div>
              <div className="text-sm text-muted-foreground">Detection Rate</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-primary">10K+</div>
              <div className="text-sm text-muted-foreground">Protected Artists</div>
            </div>
            <div>
              <div className="text-3xl font-bold text-primary">$50M+</div>
              <div className="text-sm text-muted-foreground">Art Value Protected</div>
            </div>
          </div>
        </div>
      </section>



      {/* Features Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Complete Art Protection Suite
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              From AI-powered visual recognition to blockchain verification, 
              we provide end-to-end protection for your digital artwork.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <Eye className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Visual Recognition</CardTitle>
                <CardDescription>
                  Advanced AI analyzes your artwork and detects unauthorized usage across the web
                </CardDescription>
              </CardHeader>
            </Card>
            
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <Activity className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Real-time Monitoring</CardTitle>
                <CardDescription>
                  24/7 surveillance across platforms, marketplaces, and social media networks
                </CardDescription>
              </CardHeader>
            </Card>
            
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <Link2 className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Blockchain Verification</CardTitle>
                <CardDescription>
                  Immutable proof of creation and ownership through blockchain technology
                </CardDescription>
              </CardHeader>
            </Card>
            
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <Search className="h-6 w-6 text-primary" />
                </div>
                <CardTitle>Deep Web Scanning</CardTitle>
                <CardDescription>
                  Advanced dark web monitoring and threat detection for comprehensive protection
                </CardDescription>
              </CardHeader>
            </Card>
          </div>
          
          <div className="mt-16 grid md:grid-cols-3 gap-8">
            <div className="flex items-start space-x-4">
              <div className="w-8 h-8 bg-green-500/10 rounded-full flex items-center justify-center flex-shrink-0">
                <Zap className="h-4 w-4 text-green-500" />
              </div>
              <div>
                <h3 className="font-semibold mb-2">Instant Alerts</h3>
                <p className="text-sm text-muted-foreground">Get notified immediately when your art is detected online</p>
              </div>
            </div>
            
            <div className="flex items-start space-x-4">
              <div className="w-8 h-8 bg-blue-500/10 rounded-full flex items-center justify-center flex-shrink-0">
                <Globe className="h-4 w-4 text-blue-500" />
              </div>
              <div>
                <h3 className="font-semibold mb-2">Global Coverage</h3>
                <p className="text-sm text-muted-foreground">Monitor across all major platforms and marketplaces worldwide</p>
              </div>
            </div>
            
            <div className="flex items-start space-x-4">
              <div className="w-8 h-8 bg-purple-500/10 rounded-full flex items-center justify-center flex-shrink-0">
                <Lock className="h-4 w-4 text-purple-500" />
              </div>
              <div>
                <h3 className="font-semibold mb-2">Legal Support</h3>
                <p className="text-sm text-muted-foreground">Automated DMCA filing and legal assistance when needed</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Section */}
      <section id="pricing" className="py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Choose Your Protection Plan
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              From individual artists to large studios, we have a plan that fits your needs and budget.
            </p>
          </div>
          
          <div className="grid md:grid-cols-4 gap-8">
            {/* Student Plan */}
            <Card className="border-2 border-border hover:border-primary/50 transition-colors">
              <CardHeader>
                <Badge className="mx-auto mb-4 bg-blue-600">Student</Badge>
                <CardTitle className="text-center">Student</CardTitle>
                <div className="text-center">
                  <div className="text-4xl font-bold">$19</div>
                  <div className="text-muted-foreground">/month</div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Up to 25 artworks</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Basic visual recognition</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Monthly monitoring reports</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Email support</span>
                  </div>
                </div>
                <Button 
                  className="w-full" 
                  variant="outline"
                  onClick={() => handlePricingPlan("Student")}
                >
                  Choose This Plan
                </Button>
              </CardContent>
            </Card>

            {/* Basic Plan */}
            <Card className="border-2 border-border hover:border-primary/50 transition-colors">
              <CardHeader>
                <CardTitle className="text-center">Starter</CardTitle>
                <div className="text-center">
                  <div className="text-4xl font-bold">$29</div>
                  <div className="text-muted-foreground">/month</div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Up to 50 artworks</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Basic visual recognition</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Weekly monitoring reports</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Email support</span>
                  </div>
                </div>
                <Button 
                  className="w-full" 
                  variant="outline"
                  onClick={() => handlePricingPlan("Starter")}
                >
                  Choose This Plan
                </Button>
              </CardContent>
            </Card>
            
            {/* Pro Plan */}
            <Card className="border-2 border-primary shadow-lg transform scale-105">
              <CardHeader>
                <Badge className="mx-auto mb-4 bg-primary">Most Popular</Badge>
                <CardTitle className="text-center">Professional</CardTitle>
                <div className="text-center">
                  <div className="text-4xl font-bold">$79</div>
                  <div className="text-muted-foreground">/month</div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Up to 500 artworks</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Advanced AI recognition</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Real-time monitoring</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Blockchain verification</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Automated DMCA filing</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Priority support</span>
                  </div>
                </div>
                <Button 
                  className="w-full bg-gradient-to-r from-primary to-accent"
                  onClick={() => handlePricingPlan("Professional")}
                >
                  Choose This Plan
                </Button>
              </CardContent>
            </Card>
            
            {/* Enterprise Plan */}
            <Card className="border-2 border-border hover:border-primary/50 transition-colors">
              <CardHeader>
                <CardTitle className="text-center">Enterprise</CardTitle>
                <div className="text-center">
                  <div className="text-4xl font-bold">Custom</div>
                  <div className="text-muted-foreground">pricing</div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Unlimited artworks</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Custom AI models</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Deep web scanning</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">API access</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Dedicated support</span>
                  </div>
                  <div className="flex items-center space-x-3">
                    <Check className="h-4 w-4 text-green-500" />
                    <span className="text-sm">Legal assistance</span>
                  </div>
                </div>
                <Button 
                  className="w-full" 
                  variant="outline"
                  onClick={() => navigate('/contact')}
                >
                  Contact Sales
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Trusted by Leading Artists
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              See what creative professionals are saying about TSMO's art protection platform.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8">
            <Card className="border-0 shadow-lg">
              <CardContent className="pt-6">
                <div className="flex mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                <p className="text-muted-foreground mb-4">
                  "TSMO caught someone selling my artwork on three different platforms. 
                  The automated DMCA filing saved me weeks of manual work."
                </p>
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-r from-primary to-accent rounded-full"></div>
                  <div>
                    <div className="font-semibold">Sarah Chen</div>
                    <div className="text-sm text-muted-foreground">Digital Artist</div>
                  </div>
                </div>
              </CardContent>
            </Card>
            
            <Card className="border-0 shadow-lg">
              <CardContent className="pt-6">
                <div className="flex mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                <p className="text-muted-foreground mb-4">
                  "The blockchain verification gives me peace of mind. 
                  I now have immutable proof of when I created each piece."
                </p>
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-r from-accent to-primary rounded-full"></div>
                  <div>
                    <div className="font-semibold">Marcus Rodriguez</div>
                    <div className="text-sm text-muted-foreground">NFT Creator</div>
                  </div>
                </div>
              </CardContent>
            </Card>
            
            <Card className="border-0 shadow-lg">
              <CardContent className="pt-6">
                <div className="flex mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                  ))}
                </div>
                <p className="text-muted-foreground mb-4">
                  "As a studio managing hundreds of artworks, TSMO's enterprise solution 
                  is exactly what we needed. The ROI is incredible."
                </p>
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-gradient-to-r from-primary to-accent rounded-full"></div>
                  <div>
                    <div className="font-semibold">Alex Thompson</div>
                    <div className="text-sm text-muted-foreground">Studio Director</div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
          
          <div className="text-center mt-12">
            <div className="flex items-center justify-center space-x-8 text-muted-foreground">
              <div className="flex items-center space-x-2">
                <TrendingUp className="h-5 w-5" />
                <span>500% increase in art recovery</span>
              </div>
              <div className="flex items-center space-x-2">
                <Users className="h-5 w-5" />
                <span>10,000+ protected artists</span>
              </div>
              <div className="flex items-center space-x-2">
                <Shield className="h-5 w-5" />
                <span>99.9% threat detection rate</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Legal Sources Section */}
      <section className="py-20 px-4 bg-gradient-to-br from-muted/10 to-background">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-bold mb-6">
              Legal Resources & Support
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Access comprehensive legal resources to protect your creative work. 
              From DMCA guides to copyright law, we've got you covered.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mb-12">
            {/* DMCA Resources */}
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-red-500/10 rounded-lg flex items-center justify-center mb-4">
                  <Shield className="h-6 w-6 text-red-500" />
                </div>
                <CardTitle>DMCA Takedown Guide</CardTitle>
                <CardDescription>
                  Step-by-step instructions for filing DMCA takedown requests
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">How to identify copyright infringement</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Proper DMCA notice formatting</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Platform-specific submission guides</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Follow-up procedures</span>
                  </div>
                </div>
                <Button 
                  className="w-full mt-4" 
                  variant="outline"
                  onClick={() => window.open('https://www.copyright.gov/dmca/', '_blank')}
                >
                  <Link2 className="h-4 w-4 mr-2" />
                  Access DMCA Guide
                </Button>
              </CardContent>
            </Card>

            {/* Copyright Law Resources */}
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-blue-500/10 rounded-lg flex items-center justify-center mb-4">
                  <FileImage className="h-6 w-6 text-blue-500" />
                </div>
                <CardTitle>Copyright Law Basics</CardTitle>
                <CardDescription>
                  Understanding your rights as a creative professional
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">What copyright protects</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Duration of copyright protection</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Fair use guidelines</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">International copyright law</span>
                  </div>
                </div>
                <Button 
                  className="w-full mt-4" 
                  variant="outline"
                  onClick={() => window.open('https://www.copyright.gov/help/faq/', '_blank')}
                >
                  <FileImage className="h-4 w-4 mr-2" />
                  Learn Copyright Law
                </Button>
              </CardContent>
            </Card>

            {/* Legal Templates */}
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-green-500/10 rounded-lg flex items-center justify-center mb-4">
                  <Upload className="h-6 w-6 text-green-500" />
                </div>
                <CardTitle>Legal Templates</CardTitle>
                <CardDescription>
                  Download ready-to-use legal documents and templates
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">DMCA takedown notice template</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Cease and desist letter template</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Licensing agreement template</span>
                  </div>
                  <div className="flex items-center space-x-2">
                    <div className="w-2 h-2 bg-primary rounded-full"></div>
                    <span className="text-sm">Copyright registration forms</span>
                  </div>
                </div>
                <Button 
                  className="w-full mt-4" 
                  variant="outline"
                  onClick={() => {
                    const templates = [
                      'dmca-takedown-template.pdf',
                      'cease-desist-template.pdf',
                      'licensing-agreement-template.pdf',
                      'copyright-registration-form.pdf'
                    ];
                    toast({
                      title: "Templates Download Ready",
                      description: "Legal templates package will be sent to your email.",
                    });
                  }}
                >
                  <Upload className="h-4 w-4 mr-2" />
                  Download Templates
                </Button>
              </CardContent>
            </Card>
          </div>

          {/* Legal Authorities & Resources */}
          <div className="grid md:grid-cols-2 gap-8 mb-12">
            <Card className="border-0 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Globe className="h-5 w-5 text-primary" />
                  Official Legal Authorities
                </CardTitle>
                <CardDescription>
                  Direct links to government and official legal resources
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                    <div>
                      <div className="font-medium">US Copyright Office</div>
                      <div className="text-sm text-muted-foreground">Official copyright registration</div>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => window.open('https://www.copyright.gov/', '_blank')}
                    >
                      <Link2 className="h-4 w-4 mr-1" />
                      Visit
                    </Button>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                    <div>
                      <div className="font-medium">WIPO</div>
                      <div className="text-sm text-muted-foreground">World Intellectual Property Organization</div>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => window.open('https://www.wipo.int/', '_blank')}
                    >
                      <Link2 className="h-4 w-4 mr-1" />
                      Visit
                    </Button>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                    <div>
                      <div className="font-medium">EU Copyright</div>
                      <div className="text-sm text-muted-foreground">European Union copyright resources</div>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => window.open('https://euipo.europa.eu/ohimportal/en/web/observatory/faqs-on-copyright', '_blank')}
                    >
                      <Link2 className="h-4 w-4 mr-1" />
                      Visit
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Users className="h-5 w-5 text-primary" />
                  Legal Support Network
                </CardTitle>
                <CardDescription>
                  Connect with legal professionals and support organizations
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                    <div>
                      <div className="font-medium">IP Lawyers Directory</div>
                      <div className="text-sm text-muted-foreground">Find specialized IP attorneys nationwide</div>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => navigate('/lawyers')}
                    >
                      <Search className="h-4 w-4 mr-1" />
                      Browse
                    </Button>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                    <div>
                      <div className="font-medium">Legal Aid Organizations</div>
                      <div className="text-sm text-muted-foreground">Free legal assistance for artists nationwide</div>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => {
                        toast({
                          title: "Opening Legal Aid Resources",
                          description: "Multiple legal aid organizations are being opened to help you find free assistance.",
                        });
                        // Open comprehensive legal aid directory
                        window.open('https://www.lsc.gov/find-legal-aid', '_blank');
                        setTimeout(() => {
                          // Also open volunteer lawyers for the arts
                          window.open('https://www.vlany.org/programs/arts-and-entertainment-law/', '_blank');
                        }, 500);
                        setTimeout(() => {
                          // California lawyers for the arts
                          window.open('https://calawyersforthearts.org/', '_blank');
                        }, 1000);
                      }}
                    >
                      <Link2 className="h-4 w-4 mr-1" />
                      Find Help
                    </Button>
                  </div>
                  <div className="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                    <div>
                      <div className="font-medium">Artist Legal Groups</div>
                      <div className="text-sm text-muted-foreground">Professional artist associations</div>
                    </div>
                    <Button 
                      size="sm" 
                      variant="outline"
                      onClick={() => window.open('https://www.artistsrights.org/', '_blank')}
                    >
                      <Link2 className="h-4 w-4 mr-1" />
                      Join
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>

        </div>
      </section>

      {/* Submit Testimonial Section */}
      <section className="py-20 px-4 bg-gradient-to-r from-muted/20 to-background">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Share Your TSMO Experience
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Help other artists learn about TSMO by sharing your success story
            </p>
          </div>

          <Card className="border-0 shadow-xl bg-card/80 backdrop-blur-sm">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Star className="w-5 h-5 text-primary" />
                Write Your Testimonial
              </CardTitle>
              <CardDescription>
                Tell us how TSMO has helped protect your creative work
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={(e) => {
                e.preventDefault();
                toast({
                  title: "Thank you!",
                  description: "Your testimonial has been submitted for review.",
                });
              }} className="space-y-6">
                <div className="grid md:grid-cols-2 gap-4">
                  <div>
                    <label className="text-sm font-medium mb-2 block">Your Name</label>
                    <Input placeholder="Sarah Chen" required />
                  </div>
                  <div>
                    <label className="text-sm font-medium mb-2 block">Your Profession</label>
                    <Input placeholder="Digital Artist" required />
                  </div>
                </div>

                <div>
                  <label className="text-sm font-medium mb-2 block">Rating</label>
                  <div className="flex items-center space-x-1">
                    {[1, 2, 3, 4, 5].map((rating) => (
                      <button
                        key={rating}
                        type="button"
                        className="hover:scale-110 transition-transform"
                        onClick={(e) => {
                          const stars = e.currentTarget.parentElement?.querySelectorAll('button');
                          stars?.forEach((star, index) => {
                            const starIcon = star.querySelector('svg');
                            if (starIcon) {
                              if (index < rating) {
                                starIcon.classList.add('fill-yellow-400', 'text-yellow-400');
                                starIcon.classList.remove('text-muted-foreground');
                              } else {
                                starIcon.classList.remove('fill-yellow-400', 'text-yellow-400');
                                starIcon.classList.add('text-muted-foreground');
                              }
                            }
                          });
                        }}
                      >
                        <Star className="w-6 h-6 text-muted-foreground transition-colors cursor-pointer" />
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="text-sm font-medium mb-2 block">Your Experience</label>
                  <Textarea 
                    placeholder="Tell us how TSMO helped protect your artwork. What features did you find most valuable? How did it impact your business?"
                    rows={4}
                    required
                  />
                </div>

                <div>
                  <label className="text-sm font-medium mb-2 block">Company/Studio (Optional)</label>
                  <Input placeholder="Your studio name or leave blank" />
                </div>

                <div className="flex items-center space-x-2">
                  <input type="checkbox" id="consent" className="rounded" required />
                  <label htmlFor="consent" className="text-sm text-muted-foreground">
                    I consent to TSMO using my testimonial in marketing materials
                  </label>
                </div>

                <Button 
                  type="submit" 
                  className="w-full bg-gradient-to-r from-primary to-accent hover:from-primary/90 hover:to-accent/90"
                  size="lg"
                >
                  Submit Testimonial
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </form>
            </CardContent>
          </Card>

          <div className="text-center mt-8">
            <p className="text-sm text-muted-foreground">
              All testimonials are reviewed before publication. Thank you for helping other artists discover TSMO!
            </p>
          </div>
        </div>
      </section>

      {/* Legal Templates Section */}
      <section className="py-20 px-4 bg-muted/20">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Free Legal Templates
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Download professional legal templates to protect your creative work
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <Shield className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">DMCA Takedown Notice</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Complete template for copyright infringement claims
                </p>
                <Button 
                  size="sm" 
                  className="w-full"
                  onClick={() => {
                    const content = `DMCA TAKEDOWN NOTICE

To: [Service Provider/Website Owner]
Date: [Date]

RE: Notice of Infringement under Digital Millennium Copyright Act (DMCA)

Dear Sir/Madam,

I am writing to notify you of copyright infringement occurring on your platform.

COPYRIGHT OWNER INFORMATION:
Name: [Your Full Name]
Title: [Your Title]
Company: [Company Name (if applicable)]
Address: [Your Full Address]
Phone: [Your Phone Number]
Email: [Your Email Address]

COPYRIGHTED WORK:
I am the owner of the following copyrighted work:
- Title: [Title of Your Work]
- Description: [Detailed description of your copyrighted work]
- Date of Creation: [Date]
- Registration Number: [Copyright registration number if applicable]

INFRINGING MATERIAL:
The following material on your website infringes my copyright:
- URL: [Full URL of infringing content]
- Description of Infringement: [How your work is being used without permission]

GOOD FAITH STATEMENT:
I have a good faith belief that use of the copyrighted material described above is not authorized by the copyright owner, its agent, or the law.

ACCURACY STATEMENT:
I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner or am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.

ELECTRONIC SIGNATURE:
[Your Full Legal Name]
[Date]

Please remove or disable access to the infringing material immediately.

Thank you for your prompt attention to this matter.

Sincerely,
[Your Signature]
[Your Printed Name]`;

                    downloadPDF('DMCA Takedown Notice', content);
                  }}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <FileText className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">Art Licensing Agreement</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Standard licensing template for artwork usage
                </p>
                <Button 
                  size="sm" 
                  className="w-full"
                  onClick={() => {
                    const content = `ARTWORK LICENSING AGREEMENT

This Licensing Agreement ("Agreement") is entered into on [Date] between:

LICENSOR:
[Your Name/Company]
[Address]
[Contact Information]

LICENSEE:
[Licensee Name/Company]
[Address]
[Contact Information]

1. LICENSED ARTWORK
The artwork being licensed includes:
- Title: [Artwork Title]
- Description: [Detailed description]
- Medium: [Digital/Physical/etc.]

2. GRANT OF LICENSE
Licensor grants Licensee a [exclusive/non-exclusive] license to use the artwork for:
[Specific uses allowed]

3. TERM
This license is effective from [Start Date] to [End Date].

4. TERRITORY
This license applies to: [Geographic limitations]

5. ROYALTIES AND PAYMENT
Licensee agrees to pay:
- License Fee: $[Amount]
- Royalty Rate: [Percentage]% of net sales
- Payment Schedule: [Payment terms]

6. QUALITY CONTROL
Licensee must maintain quality standards and submit samples for approval.

7. COPYRIGHT NOTICE
All uses must include: "© [Year] [Your Name]. All rights reserved."

8. TERMINATION
This agreement may be terminated by either party with [Notice Period] written notice.

9. GOVERNING LAW
This agreement is governed by the laws of [State/Country].

SIGNATURES:
Licensor: _________________ Date: _______
Licensee: _________________ Date: _______`;

                    downloadPDF('Art Licensing Agreement', content);
                  }}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardContent className="p-6">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mb-4">
                  <Scale className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">Copyright Registration Guide</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Step-by-step guide for copyright registration
                </p>
                <Button 
                  size="sm" 
                  className="w-full"
                  onClick={() => {
                    const content = `COPYRIGHT REGISTRATION GUIDE

WHY REGISTER YOUR COPYRIGHT?
- Legal presumption of ownership
- Ability to sue for infringement
- Eligibility for statutory damages
- Public record of your claim

WHAT CAN BE REGISTERED?
- Original artistic works
- Digital artwork
- Photographs
- Graphic designs
- Sculptures and installations

REGISTRATION PROCESS:

STEP 1: GATHER MATERIALS
- Completed application (Form CO or Form VA)
- Non-refundable filing fee ($45-$125)
- Copy of your work (deposit copy)

STEP 2: COMPLETE APPLICATION
Online at www.copyright.gov:
- Title of work
- Author information
- Creation date
- Publication date (if applicable)
- Rights and permissions

STEP 3: SUBMIT DEPOSIT
For artwork, submit:
- High-resolution digital files
- Physical copies (if required)
- Identifying material

STEP 4: PAY FEES
- Standard application: $125
- Online filing: $45-$65
- Group registration: varies

STEP 5: WAIT FOR PROCESSING
- Processing time: 3-12 months
- Certificate mailed upon approval
- Registration effective from submission date

TIPS FOR SUCCESS:
- Use consistent naming
- Keep detailed records
- Register promptly after creation
- Consider group registrations for multiple works

INTERNATIONAL PROTECTION:
- File in target countries
- Use Madrid Protocol for trademarks
- Consider international copyright treaties

For questions, contact:
U.S. Copyright Office
Library of Congress
Washington, DC 20559
(877) 476-0778`;

                    downloadPDF('Copyright Registration Guide', content);
                  }}
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download
                </Button>
              </CardContent>
            </Card>
          </div>

          <div className="text-center">
            <Button 
              variant="outline" 
              size="lg"
              onClick={() => navigate('/legal-templates')}
              className="flex items-center gap-2"
            >
              View All Templates
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </section>

      {/* Quick Start Section */}
      <section className="py-20 px-4 bg-muted/30">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold mb-4">
              Quick Start
            </h2>
            <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
              Get started with TSMO's powerful art protection tools in minutes
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-6">
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardContent className="p-6 text-center">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Eye className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">Visual Recognition Demo</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Test our AI-powered image recognition technology
                </p>
                <Button 
                  variant="outline" 
                  className="w-full"
                  onClick={() => window.open('/upload', '_blank')}
                >
                  Try Demo
                </Button>
              </CardContent>
            </Card>
            
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardContent className="p-6 text-center">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Link2 className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">Blockchain Certificate</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Create an immutable proof of ownership
                </p>
                <Button 
                  variant="outline" 
                  className="w-full"
                  onClick={() => window.open('/upload', '_blank')}
                >
                  Get Certificate
                </Button>
              </CardContent>
            </Card>
            
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardContent className="p-6 text-center">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Activity className="h-6 w-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">Monitoring Trial</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Start protecting your art with real-time monitoring
                </p>
                <Button 
                  variant="outline" 
                  className="w-full"
                  onClick={() => window.open('/monitoring', '_blank')}
                >
                  Start Trial
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

    </div>
  );
};

export default Index;