import { serve } from "https://deno.land/std@0.192.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.50.5';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      {
        global: {
          headers: { Authorization: req.headers.get('Authorization')! },
        },
      }
    );

    const { action, violationId, userId } = await req.json();

    if (action === 'initiate') {
      // Get violation details
      const { data: violation, error: violationError } = await supabaseClient
        .from('ai_training_violations')
        .select('*')
        .eq('id', violationId)
        .single();

      if (violationError) throw violationError;

      // Generate DMCA notice
      const noticeContent = generateDMCANotice(violation);
      
      // Create takedown record
      const { data: takedown, error: takedownError } = await supabaseClient
        .from('ai_protection_dmca_notices')
        .insert({
          user_id: userId,
          violation_id: violationId,
          status: 'filed',
          platform: violation.source_domain || 'unknown',
          takedown_url: violation.source_url || '',
          reference_number: `DMCA-${Date.now()}`,
          filed_at: new Date().toISOString(),
          metadata: { notice: noticeContent, compliance_deadline: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000).toISOString() }
        })
        .select()
        .single();

      if (takedownError) throw takedownError;

      // Simulate sending notice (in production, this would integrate with platform APIs)
      console.log('DMCA Notice sent for violation:', violationId);
      console.log('Notice content:', noticeContent);

      // Update violation status
      await supabaseClient
        .from('ai_training_violations')
        .update({ 
          status: 'dmca_sent',
          metadata: { dmca_takedown_id: takedown.id }
        })
        .eq('id', violationId);

      return new Response(
        JSON.stringify({ 
          success: true, 
          takedown,
          message: 'DMCA takedown initiated successfully'
        }),
        { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    return new Response(
      JSON.stringify({ error: 'Invalid action' }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (error) {
    console.error('Error in DMCA automation:', error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});

function generateDMCANotice(violation: any): string {
  const currentDate = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });

  return `
DMCA TAKEDOWN NOTICE

Date: ${currentDate}

To: ${violation.source_domain || 'Platform Operator'}

I am writing to notify you of copyright infringement occurring on your platform.

IDENTIFICATION OF COPYRIGHTED WORK:
The copyrighted work at issue is the original creative content protected under copyright law.

IDENTIFICATION OF INFRINGING MATERIAL:
The infringing material is located at: ${violation.source_url || 'URL not specified'}

Violation Type: ${violation.violation_type}
Detection Confidence: ${(violation.confidence_score * 100).toFixed(1)}%
Detection Method: ${violation.detection_method || 'AI-powered analysis'}

STATEMENT OF GOOD FAITH BELIEF:
I have a good faith belief that the use of the copyrighted material described above is not authorized by the copyright owner, its agent, or the law.

STATEMENT OF ACCURACY:
I declare, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner or authorized to act on behalf of the owner.

REQUESTED ACTION:
I request that you immediately remove or disable access to the infringing material.

COMPLIANCE DEADLINE:
Please respond within 10 business days of receipt of this notice.

Contact Information:
TSMO AI Protection System
Automated Copyright Protection Division

This is an automated notice generated by TSMO's AI-powered copyright protection system.
For questions or counter-notices, please contact our legal department.
`;
}
